### ISSUE TITLE
RetinaNet

### ISSUE THREAD

**Issue by mathmanu** [roytseng-tw/mask-rcnn.pytorch#4]
Is RetinaNet (or any other single stage detector) training/inference supported? I saw some field that correspond to RetinaNet in config.py - hence this question.

Thanks,

**Comment by roytseng-tw** [comment]
No, RetinaNet is not supported yet. Supported network modules are list in [here](https://github.com/roytseng-tw/mask-rcnn.pytorch#supported-network-modules).
